/**
 * FASE 17-23 - local composition. No AI is involved in the final assembly, and
 * every on-screen word is drawn by FFmpeg, never generated by a model.
 *
 * Pipeline: clip -> normalised segment (+ caption) -> intro/outro -> xfade chain ->
 * optional music -> single H.264 deliverable.
 */
import { existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { even, probe, runFfmpeg } from "./ffmpeg.mjs";
import { labRoot, relativeToLab, tempDir } from "./paths.mjs";
import { INTRO_SUBTITLE, INTRO_TITLE, OUTRO_TITLE } from "./prompt.mjs";
import { log } from "./log.mjs";

export const CROSSFADE_SECONDS = 0.5;
export const INTRO_SECONDS = 3;
export const OUTRO_SECONDS = 3.5;
export const MUSIC_VOLUME = 0.35;
const LABEL_DIR = path.join(tempDir, "labels");
const SEGMENT_DIR = path.join(tempDir, "segments");
const PAD_COLOR = "0x0B1B33";
const BRAND_BLUE = "0x1957E0";
const BRAND_BLUE_DARK = "0x123A7C";

const FONT_CANDIDATES = [
  "C:\\Windows\\Fonts\\segoeuib.ttf",
  "C:\\Windows\\Fonts\\arialbd.ttf",
  "C:\\Windows\\Fonts\\arial.ttf"
];
const BODY_FONT_CANDIDATES = ["C:\\Windows\\Fonts\\segoeui.ttf", "C:\\Windows\\Fonts\\arial.ttf"];

function firstExisting(candidates) {
  return candidates.find((candidate) => existsSync(candidate));
}

/** ffmpeg filter arguments treat `:` and `\` specially, including on Windows paths. */
function escapeForFilter(value) {
  return value.replace(/\\/g, "/").replace(/:/g, "\\:");
}

function drawText({ textFile, fontFile, fontSize, x, y, color = "white", box, alphaExpression, enableExpression }) {
  const parts = [
    `fontfile='${escapeForFilter(fontFile)}'`,
    `textfile='${relativeToLab(textFile)}'`,
    `fontcolor=${color}`,
    `fontsize=${fontSize}`,
    `x=${x}`,
    `y=${y}`
  ];
  if (box) parts.push("box=1", `boxcolor=${box}`, "boxborderw=22");
  if (alphaExpression) parts.push(`alpha='${alphaExpression}'`);
  if (enableExpression) parts.push(`enable='${enableExpression}'`);
  return `drawtext=${parts.join(":")}`;
}

/**
 * Caption fade window, expressed against the segment's own timeline.
 * Short clips get a tighter window so the text never outlives the shot.
 */
export function captionAlphaExpression(durationSeconds, { start = 0.7, end = 0.8, fade = 0.6 } = {}) {
  const fadeInEnd = start + fade;
  const fadeOutStart = Math.max(fadeInEnd + 0.1, durationSeconds - end - fade);
  return `min(1,max(0,(t-${start.toFixed(2)})/${fade.toFixed(2)}))*min(1,max(0,(${fadeOutStart.toFixed(2)}+${fade.toFixed(2)}-t)/${fade.toFixed(2)}))`;
}

async function writeLabel(name, content) {
  await mkdir(LABEL_DIR, { recursive: true });
  const file = path.join(LABEL_DIR, `${name}.txt`);
  await writeFile(file, content, "utf8");
  return file;
}

function introBackgroundSource({ width, height, seconds, filters }) {
  if (filters.has("gradients")) {
    return ["-f", "lavfi", "-i", `gradients=s=${width}x${height}:c0=${BRAND_BLUE_DARK}:c1=${BRAND_BLUE}:nb_colors=2:d=${seconds}`];
  }
  return ["-f", "lavfi", "-i", `color=c=${PAD_COLOR}:s=${width}x${height}:d=${seconds}`];
}

/** FASE 19 / FASE 22 - a short, restrained intro. */
export async function buildIntro({ width, height, logoPath, outputPath, filters }) {
  const seconds = INTRO_SECONDS;
  const titleFont = firstExisting(FONT_CANDIDATES);
  const bodyFont = firstExisting(BODY_FONT_CANDIDATES);
  const titleLabel = await writeLabel("intro-title", INTRO_TITLE);
  const subtitleLabel = await writeLabel("intro-subtitle", INTRO_SUBTITLE);

  const titleSize = Math.max(40, Math.round((width / 1920) * 84));
  const subtitleSize = Math.max(20, Math.round((width / 1920) * 34));

  const chain = [
    drawText({
      textFile: titleLabel,
      fontFile: titleFont,
      fontSize: titleSize,
      x: "(w-text_w)/2",
      y: logoPath ? "h*0.50" : "(h-text_h)/2",
      color: "white",
      alphaExpression: `min(1,max(0,(t-0.25)/0.7))*min(1,max(0,(${seconds - 0.35}-t)/0.6))`
    }),
    drawText({
      textFile: subtitleLabel,
      fontFile: bodyFont,
      fontSize: subtitleSize,
      x: "(w-text_w)/2",
      y: logoPath ? "h*0.50+text_h*1.9" : "(h+text_h)/2+44",
      color: "0xD8E4F5",
      alphaExpression: `min(1,max(0,(t-0.7)/0.7))*min(1,max(0,(${seconds - 0.35}-t)/0.6))`
    })
  ];

  // The logo never sits on top of a software screenshot: it only appears on the
  // intro/outro cards.
  const args = [...introBackgroundSource({ width, height, seconds, filters })];
  let filter;
  if (logoPath) {
    args.push("-i", logoPath);
    const logoWidth = Math.round(width * 0.2);
    filter = [
      `[1:v]scale=${logoWidth}:-1[logo]`,
      `[0:v]${chain.join(",")}[bg]`,
      `[bg][logo]overlay=(main_w-overlay_w)/2:main_h*0.26:format=auto[vout]`
    ].join(";");
  } else {
    filter = `[0:v]${chain.join(",")}[vout]`;
  }

  args.push(
    "-filter_complex", filter,
    "-map", "[vout]",
    "-t", String(seconds),
    "-r", "30",
    "-c:v", "libx264", "-preset", "medium", "-crf", "18", "-pix_fmt", "yuv420p",
    outputPath
  );
  await mkdir(path.dirname(outputPath), { recursive: true });
  await runFfmpeg(args, { label: "intro build" });
  return outputPath;
}

/** FASE 19 - outro with the verified 7-day trial message. */
export async function buildOutro({ width, height, logoPath, outputPath, filters, caption }) {
  const seconds = OUTRO_SECONDS;
  const titleFont = firstExisting(FONT_CANDIDATES);
  const bodyFont = firstExisting(BODY_FONT_CANDIDATES);
  const titleLabel = await writeLabel("outro-title", caption ?? OUTRO_TITLE);
  const titleSize = Math.max(30, Math.round((width / 1920) * 56));

  const chain = [
    drawText({
      textFile: titleLabel,
      fontFile: titleFont,
      fontSize: titleSize,
      x: "(w-text_w)/2",
      y: "(h-text_h)/2",
      color: "white",
      alphaExpression: `min(1,max(0,(t-0.2)/0.6))*min(1,max(0,(${seconds - 0.3}-t)/0.5))`
    })
  ];

  const args = ["-f", "lavfi", "-i", `color=c=${BRAND_BLUE_DARK}:s=${width}x${height}:d=${seconds}`];
  let filter;
  if (logoPath) {
    args.push("-i", logoPath);
    const logoWidth = Math.round(width * 0.16);
    filter = [
      `[1:v]scale=${logoWidth}:-1[logo]`,
      `[0:v]${chain.join(",")}[bg]`,
      `[bg][logo]overlay=(main_w-overlay_w)/2:main_h*0.24:format=auto[vout]`
    ].join(";");
  } else {
    filter = `[0:v]${chain.join(",")}[vout]`;
  }

  args.push(
    "-filter_complex", filter,
    "-map", "[vout]",
    "-t", String(seconds),
    "-r", "30",
    "-c:v", "libx264", "-preset", "medium", "-crf", "18", "-pix_fmt", "yuv420p",
    outputPath
  );
  await mkdir(path.dirname(outputPath), { recursive: true });
  await runFfmpeg(args, { label: "outro build" });
  return outputPath;
}

/**
 * Normalises one generated clip and bakes its caption in.
 * FASE 17: the caption is real text rendered by FFmpeg, not a model artefact.
 *
 * A clip whose aspect does not match the master (a portrait phone screen inside a
 * 16:9 ad, for example) is placed on a blurred, slightly darkened fill of itself
 * instead of being pillarboxed with hard black bars. The original UI pixels are
 * never rescaled non-uniformly, cropped or redrawn.
 */
export async function buildClipSegment({ clipPath, caption, index, width, height, outputPath, filters }) {
  const source = await probe(clipPath);
  const duration = source.duration ?? 5;
  const fontFile = firstExisting(FONT_CANDIDATES);
  const label = caption ? await writeLabel(`segment-${String(index).padStart(2, "0")}`, caption) : undefined;

  const finalisers = ["setsar=1", "fps=30"];
  if (label) {
    const fontSize = Math.max(22, Math.round((width / 1920) * 40));
    finalisers.push(
      drawText({
        textFile: label,
        fontFile,
        fontSize,
        x: Math.round(width * 0.045),
        y: `h-text_h-${Math.round(height * 0.09)}`,
        color: "white",
        box: "0x0B1B33@0.55",
        alphaExpression: captionAlphaExpression(duration)
      })
    );
  }

  const sourceAspect = (source.width ?? width) / (source.height ?? height);
  const targetAspect = width / height;
  const aspectMismatch = Math.abs(sourceAspect - targetAspect) / targetAspect > 0.05;

  await mkdir(path.dirname(outputPath), { recursive: true });
  const encode = ["-an", "-r", "30", "-c:v", "libx264", "-preset", "medium", "-crf", "18", "-pix_fmt", "yuv420p", outputPath];

  if (aspectMismatch) {
    const plateWidth = even(width * 0.94);
    const plateHeight = even(height * 0.94);
    const blur = filters?.has("gblur") ? "gblur=sigma=36" : "boxblur=luma_radius=36:luma_power=2";
    const dim = filters?.has("eq") ? ",eq=brightness=-0.12" : "";
    const graph = [
      "[0:v]split=2[bg][fg]",
      `[bg]scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height},${blur}${dim}[bgout]`,
      `[fg]scale=${plateWidth}:${plateHeight}:force_original_aspect_ratio=decrease[fgout]`,
      "[bgout][fgout]overlay=(W-w)/2:(H-h)/2:format=auto[stage]",
      `[stage]${finalisers.join(",")}[vout]`
    ].join(";");
    await runFfmpeg(
      ["-i", clipPath, "-filter_complex", graph, "-map", "[vout]", ...encode],
      { label: `segment ${index} (blur fill)` }
    );
  } else {
    const chain = [
      `scale=${width}:${height}:force_original_aspect_ratio=decrease,pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2:color=${PAD_COLOR}`,
      ...finalisers
    ];
    await runFfmpeg(["-i", clipPath, "-vf", chain.join(","), ...encode], { label: `segment ${index}` });
  }

  return { path: outputPath, duration: (await probe(outputPath)).duration ?? duration, blurFilled: aspectMismatch };
}

/** Chains segments with restrained crossfades and returns the total duration. */
export async function crossfadeSegments({ segments, outputPath, transition = "fade" }) {
  if (segments.length === 1) {
    await runFfmpeg(["-i", segments[0].path, "-c", "copy", outputPath], { label: "single segment copy" });
    return { duration: segments[0].duration, steps: 0 };
  }

  const args = [];
  for (const segment of segments) args.push("-i", segment.path);

  const parts = [];
  let running = segments[0].duration;
  let previousLabel = "0:v";
  let steps = 0;

  for (let index = 1; index < segments.length; index += 1) {
    const offset = Math.max(0, running - CROSSFADE_SECONDS);
    const label = `v${index}`;
    parts.push(
      `[${previousLabel}][${index}:v]xfade=transition=${transition}:duration=${CROSSFADE_SECONDS}:offset=${offset.toFixed(3)}[${label}]`
    );
    running = running + segments[index].duration - CROSSFADE_SECONDS;
    previousLabel = label;
    steps += 1;
  }

  args.push(
    "-filter_complex", parts.join(";"),
    "-map", `[${previousLabel}]`,
    "-r", "30",
    "-c:v", "libx264", "-preset", "medium", "-crf", "18", "-pix_fmt", "yuv420p",
    "-movflags", "+faststart",
    outputPath
  );

  await mkdir(path.dirname(outputPath), { recursive: true });
  await runFfmpeg(args, { label: "crossfade assembly" });
  return { duration: Number(running.toFixed(3)), steps };
}

/** FASE 21 - music if the user supplied it, silence otherwise. Never downloads anything. */
export async function muxMusic({ videoPath, audioPath, outputPath, duration }) {
  if (!audioPath) {
    await runFfmpeg(["-i", videoPath, "-c", "copy", "-movflags", "+faststart", outputPath], { label: "final remux (no audio)" });
    return { audio: false };
  }

  const fadeOutStart = Math.max(0.5, duration - 2);
  const chain = [
    `atrim=0:${duration.toFixed(3)}`,
    "asetpts=PTS-STARTPTS",
    `volume=${MUSIC_VOLUME}`,
    "afade=t=in:st=0:d=1.5",
    `afade=t=out:st=${fadeOutStart.toFixed(2)}:d=2`
  ].join(",");

  await mkdir(path.dirname(outputPath), { recursive: true });
  await runFfmpeg(
    [
      "-i", videoPath,
      "-stream_loop", "-1", "-i", audioPath,
      "-filter_complex", `[1:a]${chain}[aout]`,
      "-map", "0:v", "-map", "[aout]",
      "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
      "-shortest",
      "-movflags", "+faststart",
      outputPath
    ],
    { label: "music mux" }
  );
  return { audio: true };
}

/**
 * FASE 23 - the 16:9 master is produced now; 9:16 and 1:1 are derived from it on
 * demand with the same deterministic crop.
 */
export function buildFormatsPlan({ masterPath, masterWidth, masterHeight }) {
  const verticalWidth = 1080;
  const verticalHeight = 1920;
  const square = 1080;
  return {
    master: {
      path: masterPath,
      resolution: `${masterWidth}x${masterHeight}`,
      aspect: "16:9",
      status: "generated"
    },
    derived: [
      {
        aspect: "9:16",
        status: "prepared",
        purpose: "Reels / Stories / Shorts",
        target: `${verticalWidth}x${verticalHeight}`,
        filter: `scale=${verticalWidth}:${verticalHeight}:force_original_aspect_ratio=increase,crop=${verticalWidth}:${verticalHeight},setsar=1`,
        command: `ffmpeg -i <master> -vf "scale=${verticalWidth}:${verticalHeight}:force_original_aspect_ratio=increase,crop=${verticalWidth}:${verticalHeight},setsar=1" -c:v libx264 -crf 20 -preset medium -pix_fmt yuv420p <out-9x16.mp4>`
      },
      {
        aspect: "1:1",
        status: "prepared",
        purpose: "Feed posts",
        target: `${square}x${square}`,
        filter: `scale=${square}:${square}:force_original_aspect_ratio=increase,crop=${square}:${square},setsar=1`,
        command: `ffmpeg -i <master> -vf "scale=${square}:${square}:force_original_aspect_ratio=increase,crop=${square}:${square},setsar=1" -c:v libx264 -crf 20 -preset medium -pix_fmt yuv420p <out-1x1.mp4>`
      }
    ]
  };
}

/** Renders a derived aspect ratio from the finished master. */
export async function renderDerived({ masterPath, spec, outputPath }) {
  await runFfmpeg(
    [
      "-i", masterPath,
      "-vf", spec.filter,
      "-c:v", "libx264", "-crf", "20", "-preset", "medium", "-pix_fmt", "yuv420p",
      "-c:a", "copy",
      "-movflags", "+faststart",
      outputPath
    ],
    { label: `derived format ${spec.aspect}` }
  );
  return outputPath;
}

/**
 * FASE 18 - full assembly used by the CLI.
 * `clips` = [{ path, caption, index }]
 */
export async function composeFinalVideo({
  clips,
  logoPath,
  audioPath,
  outputPath,
  resolution,
  filters,
  enableIntro = true,
  enableOutro = true,
  keepSegments = true
}) {
  const width = even(resolution?.width ?? 1280);
  const height = even(resolution?.height ?? 720);

  log.step(`composing ${clips.length} clip(s) at ${width}x${height}`);
  await mkdir(SEGMENT_DIR, { recursive: true });

  const segments = [];
  if (enableIntro) {
    const intro = path.join(SEGMENT_DIR, "00-intro.mp4");
    await buildIntro({ width, height, logoPath, outputPath: intro, filters });
    segments.push({ path: intro, duration: (await probe(intro)).duration ?? INTRO_SECONDS, kind: "intro" });
  }

  for (const [position, clip] of clips.entries()) {
    const target = path.join(SEGMENT_DIR, `${String(position + 1).padStart(2, "0")}-clip.mp4`);
    const segment = await buildClipSegment({
      clipPath: clip.path,
      caption: clip.caption,
      index: clip.index ?? position + 1,
      width,
      height,
      outputPath: target,
      filters
    });
    segments.push({ ...segment, kind: "clip" });
    log.detail(
      `segment ${position + 1}: ${clip.caption ?? "(no caption)"} (${segment.duration.toFixed(2)}s${segment.blurFilled ? ", blur-filled background" : ""})`
    );
  }

  if (enableOutro) {
    const outro = path.join(SEGMENT_DIR, `${String(clips.length + 1).padStart(2, "0")}-outro.mp4`);
    await buildOutro({ width, height, logoPath, outputPath: outro, filters });
    segments.push({ path: outro, duration: (await probe(outro)).duration ?? OUTRO_SECONDS, kind: "outro" });
  }

  const assembled = path.join(tempDir, "assembled.mp4");
  const { duration } = await crossfadeSegments({ segments, outputPath: assembled });
  log.detail(`crossfades: ${segments.length - 1} x ${CROSSFADE_SECONDS}s -> ${duration.toFixed(2)}s`);

  const muxed = await muxMusic({ videoPath: assembled, audioPath, outputPath, duration });

  return {
    outputPath,
    duration,
    width,
    height,
    audio: muxed.audio,
    segmentCount: segments.length,
    segments: segments.map((segment) => ({ kind: segment.kind, path: relativeToLab(segment.path), duration: segment.duration, blurFilled: Boolean(segment.blurFilled) })),
    labelDir: relativeToLab(LABEL_DIR)
  };
}

/** Removes stale segment output so a recompose cannot mix old and new clips. */
export async function clearSegments() {
  try {
    const entries = await readdir(SEGMENT_DIR);
    for (const entry of entries) {
      await rm(path.join(SEGMENT_DIR, entry), { recursive: true, force: true });
    }
  } catch {
    /* nothing to clear */
  }
  await mkdir(SEGMENT_DIR, { recursive: true });
  return SEGMENT_DIR;
}

export function segmentsDirectory() {
  return SEGMENT_DIR;
}

/**
 * FASE 23 - the master is 16:9 at the best resolution the LANDSCAPE sources can
 * back. A portrait clip must be fitted into the master later, never allowed to
 * drag the master into a vertical aspect of its own.
 */
export function masterResolution(clips, { maxWidth = 1920, maxHeight = 1080 } = {}) {
  const landscape = clips.filter((clip) => (clip.probe?.width ?? 0) >= (clip.probe?.height ?? 1));
  const basis = landscape.length > 0 ? landscape : clips;
  const widths = basis.map((clip) => clip.probe?.width ?? 0).filter((value) => value > 0);
  const widest = widths.length > 0 ? Math.max(...widths) : 1280;
  const width = even(Math.min(widest, maxWidth));
  const height = even(Math.min(Math.round((width * 9) / 16), maxHeight));
  return { width, height, basedOn: landscape.length > 0 ? "landscape clips" : "portrait clips" };
}

export function labRootPath() {
  return labRoot;
}
