/**
 * FASE 8 / FASE 17 / FASE 20 - prompt construction and on-screen copy.
 *
 * PRIORITY: the original software UI must survive. The prompts below therefore
 * ask only for restrained camera motion and explicitly forbid redrawing the
 * interface. Commercial text is NEVER generated by the model; it is added later
 * with local FFmpeg `drawtext` (see compose.mjs), because a diffusion model
 * cannot be trusted to render readable, correct marketing copy.
 */

export const UI_PRESERVATION_PROMPT = [
  "Professional SaaS product showcase of the provided point-of-sale software interface.",
  "Preserve the original UI layout, colors, text, buttons and application structure exactly.",
  "Apply only a subtle cinematic camera move: a very gentle push-in, restrained parallax depth and premium commercial lighting.",
  "The interface must stay fully recognizable, sharp and stable; screens must remain readable throughout.",
  "Screen-recording look, clean studio lighting, elegant and calm.",
  "Do not redesign the software, do not invent UI elements, do not add people or hands."
].join(" ");

export const UI_NEGATIVE_PROMPT = [
  "distorted UI",
  "warped text",
  "changed interface",
  "unreadable text",
  "invented buttons",
  "duplicated windows",
  "morphing menus",
  "garbled numbers",
  "flickering",
  "heavy motion",
  "fast camera shake",
  "people",
  "hands",
  "faces",
  "logos added",
  "watermark",
  "extra objects"
].join(", ");

/**
 * Appends the negative-prompt instruction for models that take a single string.
 */
export function promptForModel(profile, basePrompt = UI_PRESERVATION_PROMPT) {
  if (profile?.model === "wan-2-2-i2v") {
    // WAN 2.2 takes `negative_prompt` as a separate field, handled below.
    return basePrompt;
  }
  // WAN 2.6 profiles accept only a prompt in the product's contract, so the
  // constraints ride along with the positive prompt.
  return `${basePrompt} Strictly avoid: ${UI_NEGATIVE_PROMPT}.`;
}

/**
 * The product's `buildRunpodInput()` ships a generic negative prompt. For a
 * software showcase we strengthen it with UI-specific constraints, keeping the
 * product's own terms and never removing them.
 *
 * The payload is built by the product; only this one field is refined, and only
 * when the chosen model actually exposes a `negative_prompt`.
 */
export function refineProviderInput(input) {
  if (!input || typeof input !== "object" || typeof input.negative_prompt !== "string") {
    return input;
  }
  const terms = new Set();
  for (const term of `${input.negative_prompt}, ${UI_NEGATIVE_PROMPT}`.split(",")) {
    const clean = term.trim();
    if (clean) terms.add(clean);
  }
  input.negative_prompt = [...terms].join(", ");
  return input;
}

/**
 * FASE 20 - safe scene captions.
 *
 * A caption is only used when the file name gives a confident signal (e.g.
 * `01-facturacion.png`). Otherwise a neutral, non-committal phrase is used, so a
 * screen is never labelled with a function it may not show.
 */
const CAPTION_RULES = [
  // Form factor is checked FIRST: a file named `03-pos-mobile.png` must read as a
  // mobile screen, not as a generic "pos" one. Specific beats generic.
  { match: /mobile|movil|móvil|android|ios|tablet|tel[eé]fono/, caption: "Tu negocio en el bolsillo" },
  { match: /factur|billing|invoice|cobro|caja|ticket|receipt/, caption: "Facturación rápida" },
  { match: /product|invent|stock|art[ií]culo|almac|cat[aá]logo/, caption: "Control de inventario" },
  { match: /client|customer/, caption: "Gestiona tus clientes" },
  { match: /report|estad|dashboard|informe|analytic|margen|utilidad/, caption: "Información en un solo lugar" },
  { match: /venta|sale|order|pedido|carrito|cart/, caption: "Gestiona tus ventas" },
  { match: /buscar|search|b[uú]squeda|filtro|filter/, caption: "Encuentra todo en segundos" },
  { match: /login|acceso|usuario|user|registro|register/, caption: "Accede desde cualquier dispositivo" },
  { match: /pago|payment|tarjeta|card|efectivo|cash/, caption: "Cobros sin complicaciones" },
  { match: /config|ajuste|setting|licencia|plan/, caption: "Configúralo a tu medida" },
  // Generic POS wording is a last resort only, so it never overrides a more
  // specific signal such as "mobile".
  { match: /\bpos\b|\btpv\b/, caption: "Facturación rápida" }
];

const NEUTRAL_CAPTIONS = [
  "Hecho para tu negocio",
  "Todo en un solo lugar",
  "Más rápido y más simple",
  "Controla tu operación",
  "Diseñado para vender más"
];

/**
 * Chooses a caption for one image.
 *
 * `overrides` (from `input/captions.json`) always wins, so the operator can pin
 * exact wording without renaming screenshots.
 */
export function captionForImage(fileName, index, overrides = {}) {
  const declared = overrides?.[fileName];
  if (typeof declared === "string" && declared.trim()) {
    return { caption: declared.trim(), confidence: "declared", source: "input/captions.json" };
  }
  const slug = fileName.toLowerCase();
  const rule = CAPTION_RULES.find((item) => item.match.test(slug));
  if (rule) return { caption: rule.caption, confidence: "inferred", source: "file name" };
  return {
    caption: NEUTRAL_CAPTIONS[index % NEUTRAL_CAPTIONS.length],
    confidence: "generic",
    source: "neutral fallback"
  };
}

/** Reads `input/captions.json` style overrides. Bad JSON is reported, never fatal. */
export function parseCaptionOverrides(raw) {
  if (!raw || !raw.trim()) return { overrides: {}, error: undefined };
  try {
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return { overrides: {}, error: "expected a JSON object mapping file name -> caption" };
    }
    const overrides = {};
    for (const [key, value] of Object.entries(parsed)) {
      if (typeof value === "string" && value.trim()) overrides[key] = value.trim();
    }
    return { overrides, error: undefined };
  } catch (error) {
    return { overrides: {}, error: error.message };
  }
}

export const INTRO_TITLE = "FULLPOS CLOUD";
export const INTRO_SUBTITLE = "Controla tus ventas, inventario y caja";
/** Verified in the product itself - never invent offers here. */
export const OUTRO_TITLE = "Prueba FullPOS gratis por 7 días";
